### ISSUE TITLE
Empty Script

### ISSUE THREAD

**Issue by LilyDaytoy** [yuezih/Movie101#2]
Thanks for the amazing dataset! But the script is empty? When will it be accessible? Thank you!

**Comment by yuezih** [comment]
Thank you for your interest in Movie101!

Due to the security mechanisms of the video platform, scraping movies isn't a straightforward task; it involves a complex process, such as simulating page-turning. We've previously attempted to provide a convenient download script, but it proved somewhat challenging. We're currently exploring new release methods, such as directly providing the original videos after signing a consent form. 

We're striving to complete all open-source work within a week, at the latest before the commencement of ACL 2023.

**Comment by yuezih** [comment]
Hi, we've provided the way to access our data in the update just now. Please check the details at `Movie101/dataset/README.md`. Thanks!
